import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  background: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#e4e4ff',
    fontFamily: 'Orbitron_600SemiBold',
    textShadowColor: 'rgba(150, 150, 255, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    marginBottom: 20,
    textAlign: 'center',
  },
  card: {
    fontFamily: 'Exo2_300Light',
    fontSize: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 15,
    padding: 15,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  text: {
    color: '#e4e4ff',
    fontFamily: 'Exo2_400Regular',
    fontSize: 16,
    lineHeight: 24,
  },
  welcomeText: {
    color: '#e4e4ff',
    fontFamily: 'Exo2_400Regular',
    fontSize: 24,
    lineHeight: 24,
    textAlign: 'center',
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 15,
    color: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 8,
  },
  separator: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 20,
  },
  badge: {
    backgroundColor: '#2d3462',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  badgeText: {
    fontFamily: 'Orbitron_600SemiBold',
    color: '#b4b8ff',
    fontSize: 16,
    fontWeight: '500',
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: 10,
  },
  cardHeader: {
    fontFamily: 'Orbitron_600SemiBold',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardContent: {
    gap: 8,
  },
  tierContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  description: {
    color: '#e4e4ff',
    fontSize: 16,
    lineHeight: 20,
    fontFamily: 'Exo2_400Regular',
  },
  updateButton: {
    fontFamily: 'Orbitron_600SemiBold',
    backgroundColor: '#3d4db7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  deleteButton: {
    fontFamily: 'Orbitron_600SemiBold',
    backgroundColor: '#dc3545',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 8,
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 1,
  },
  backButtonText: {
    fontFamily: 'Orbitron_600SemiBold',
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  userInfoContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    width: '90%',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  contentContainer: {
    flex: 1,
    padding: 20,
    paddingTop:40,
  },
  searchInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 15,
    color: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 8,
  },
  filtersContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
    gap: 10,
  },
  tableContainer: {
    flex: 1,
    marginTop: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 12,
  },
  tableHeader: {
    color: '#b4b8ff',
    fontWeight: '600',
    fontSize: 16,
  },
  tableCell: {
    color: '#e4e4ff',
    fontSize: 16,
  },
  nameColumn: {
    flex: 2,
  },
  typeColumn: {
    flex: 1,
  },
  sourceColumn: {
    flex: 1,
  },
  planTypeColumn: {
    flex: 1,
  },
  modalCloseButton: {
    marginTop: 15,
    padding: 15,
    backgroundColor: '#3d4db7',
    borderRadius: 8,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  filterButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterButtonText: {
    color: '#e4e4ff',
    fontSize: 16,
    fontFamily: 'Orbitron_600SemiBold',
  },
  selectContainer: {
    marginVertical: 8,
  },
  pickerContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginTop: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  picker: {
    color: '#e4e4ff',
    height: 50,
    fontFamily: 'Exo2_400Regular',
    backgroundColor: 'transparent',
  },
  selectButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  selectButtonText: {
    color: '#e4e4ff',
    fontSize: 16,
    fontFamily: 'Exo2_400Regular',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#1a2151',
    padding: 20,
    borderRadius: 15,
    width: '80%',
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalTitle: {
    color: '#e4e4ff',
    fontSize: 20,
    fontFamily: 'Orbitron_600SemiBold',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalItem: {
    padding: 15,
    borderRadius: 8,
    marginVertical: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  modalItemSelected: {
    backgroundColor: '#3d4db7',
  },
  modalItemText: {
    color: '#e4e4ff',
    fontSize: 16,
    fontFamily: 'Exo2_400Regular',
  },
  modalItemTextSelected: {
    color: '#ffffff',
    fontWeight: '600',
  },
  sectionContainer: {
    marginBottom: 20,
  },
  sectionTitle: {
    color: '#e4e4ff',
    fontSize: 20,
    fontFamily: 'Orbitron_600SemiBold',
    marginBottom: 10,
  },
  statusColumn: {
    flex: 1.5,
  },
  loanedRow: {
    backgroundColor: 'rgba(61, 77, 183, 0.1)',
  },
  loanedText: {
    color: '#8f97ff',
    fontStyle: 'italic',
  },
  expendedRow: {
    opacity: 0.6,
  },
  characterRow: {
    justifyContent: 'space-between',
    gap: 10,
  },
  characterInfo: {
    gap: 5,
    marginBottom: 15,
  },
  characterName: {
    color: '#e4e4ff',
    fontSize: 16,
    fontFamily: 'Orbitron_600SemiBold',
  },
  characterType: {
    color: '#b4b8ff',
    fontSize: 16,
    fontFamily: 'Exo2_400Regular',
  },
  characterTier: {
    color: '#b4b8ff',
    fontSize: 16,
    fontFamily: 'Exo2_400Regular',
  },
  characterDescription: {
    color: '#e4e4ff',
    fontSize: 16,
    fontFamily: 'Exo2_400Regular',
    marginTop: 5,
  },
  buttonContainer: {
    gap: 8,
    backgroundColor: '#3d4db7',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginVertical: 10,
    marginHorizontal: 20,
    shadowColor: '#6d7cff',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#ffffff',
    fontFamily: 'Orbitron_600SemiBold',
    fontSize: 16,
    fontWeight: '600',
  },
  scrollContainer: {
    flex: 1,
    width: '100%',
  },
  detailCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 15,
    padding: 20,
    margin: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  label: {
    fontFamily: 'Orbitron_600SemiBold',
    color: '#b4b8ff',
    fontSize: 16,
  },
  value: {
    color: '#e4e4ff',
    fontSize: 16,
    fontFamily: 'Exo2_400Regular',
  },
  errorText: {
    color: '#ff4444',
    fontSize: 16,
    textAlign: 'center',
  },
  tableRowPressed: {
    backgroundColor: 'rgba(61, 77, 183, 0.3)',
  },
  itemInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  actionButton: {
    backgroundColor: '#3d4db7',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  secondaryButton: {
    backgroundColor: '#2d3462', // darker blue
    borderWidth: 1,
    borderColor: '#3d4db7',
  },
  dangerButton: {
    backgroundColor: '#dc3545', // red color for dangerous actions
  },
  pressable: {
    flex: 1,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  rowContainer: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  rowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
});

export default styles;