import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  background: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#e4e4ff',
    fontFamily: 'Orbitron_600SemiBold',
    textShadowColor: 'rgba(150, 150, 255, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    marginBottom: 20,
    textAlign: 'center',
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    fontFamily: 'Exo2_300Light',
    borderRadius: 15,
    padding: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  text: {
    color: '#e4e4ff',
    fontFamily: 'Exo2_400Regular',
    fontSize: 16,
    lineHeight: 24,
  },
  textLarge: {
    color: '#e4e4ff',
    fontFamily: 'Exo2_400Regular',
    fontSize: 24,
    lineHeight: 24,
  },
  buttonText: {
    color: '#ffffff',
    fontFamily: 'Orbitron_600SemiBold',
    fontSize: 16,
    fontWeight: '600',
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 15,
    color: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 8,
  },
  separator: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 20,
  },
  badge: {
    backgroundColor: '#2d3462',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  badgeText: {
    fontFamily: 'Orbitron_600SemiBold',
    color: '#b4b8ff',
    fontSize: 14,
    fontWeight: '500',
  },
  characterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: 10,
  },
  cardHeader: {
    fontFamily: 'Orbitron_600SemiBold',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardContent: {
    gap: 8,
  },
  characterName: {
    fontFamily: 'Orbitron_600SemiBold',
    fontSize: 20,
    fontWeight: '600',
    color: '#e4e4ff',
  },
  tierContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  label: {
    fontFamily: 'Orbitron_600SemiBold',
    color: '#b4b8ff',
    fontSize: 14,
    fontWeight: '500',
  },
  description: {
    color: '#e4e4ff',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Exo2_400Regular',
  },
  updateButton: {
    fontFamily: 'Orbitron_600SemiBold',
    backgroundColor: '#3d4db7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  deleteButton: {
    fontFamily: 'Orbitron_600SemiBold',
    backgroundColor: '#dc3545',  // Red color for delete
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 8,
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 1,
  },
  backButtonText: {
    fontFamily: 'Orbitron_600SemiBold',
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  userInfoContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    width: '90%', // Makes it narrower than the full width
    alignSelf: 'center', // Centers it horizontally
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  buttonContainer: {
    backgroundColor: '#3d4db7',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginVertical: 10,
    marginHorizontal: 20,
    shadowColor: '#6d7cff',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  contentContainer: {
    flex: 1,
    padding: 20,
    paddingTop:40,
  },
});

export default styles;